In [37]:
import numpy as np
from time import time
from scipy.spatial.distance import cdist

In [2]:
test = (1, 2, 3)

In [6]:
test2 = np.array([test])

In [7]:
print(test2.shape)

(1, 3)


In [8]:
joe = \
[(1, 2, 3),
 (2, 3, 4),
 (4, 5, 6),
 (5, 6, 7)]

In [12]:
joesmoe = np.array(joe)

In [71]:
begin = time()
for _ in range(10000):
    bum = cdist(test2, joesmoe, metric='euclidean')
print(time() - begin)
print(bum)

0.167965173721
[[0.         1.73205081 5.19615242 6.92820323]]


In [74]:
begin = time()
for _ in range(10000):
    bum = np.sqrt(np.dot(test2, test2.T) - 2 * np.dot(test2, joesmoe.T) + np.dot(joesmoe, joesmoe.T))
print(time() - begin)
print(bum)

0.112682819366
[[0.                nan        nan        nan]
 [2.44948974 1.73205081        nan        nan]
 [4.24264069 4.58257569 5.19615242 5.47722558]
 [4.89897949 5.47722558 6.4807407  6.92820323]]


/Users/wyin/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [73]:
begin = time()
for _ in range(10000):
    distances = []
    for line in joesmoe:
        distances.append(np.linalg.norm(test2 - line))
print(time() - begin)
print(distances)

0.32562994957
[0.0, 1.7320508075688772, 5.196152422706632, 6.928203230275509]


In [18]:
distances

[0.0, 1.7320508075688772, 5.196152422706632, 6.928203230275509]

In [22]:
np.linalg.norm((test2 - joesmoe).dot((test2 - joesmoe).T))

78.0